version: "3.2"

services:
  mysql:
    image: mysql:5.7
    env_file:
      - backend/env/.env.dev
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
  app:
    container_name: app
    build: backend
    env_file:
      - ./backend/env/.env.dev
    volumes:
      - ./backend:/app
      - static_data:/srv/static
    depends_on:
      - mysql
    expose:
      - 8000
  nginx:
    build: backend/nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./mysql_data:/var/lib/mysql
      - static_data:/srv/static:ro  # ro readonly
  angular:
    container_name: angular
    build:
      context: angular
      dockerfile: Dockerfile.dev
    depends_on:
      - app
    volumes:
       - ./angular:/app/
       - /app/node_modules
    ports:
      - "4200:4200"
volumes:
  mysql_data:
  static_data:
