version: "3.2"

services:
  mysql:
    image: mysql:5.7
    env_file:
      - backend/env/.env.dev
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
  app:
    build: backend
    env_file:
      - backend/env/.env.dev
    volumes:
      - ./backend:/app
      - static_data:/srv
    depends_on:
      - mysql
    expose:
      - 8000
  nginx:
    build: backend/nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./mysql_data:/var/lib/mysql
#      - ./config/nginx:/etc/nginx/conf.d
      - static_data:/srv:ro  # ro readonly
volumes:
  mysql_data:
  static_data:
