FROM node:12.0-alpine as builder

# Set working directory.
RUN mkdir /app
WORKDIR /app

# Copy app dependencies.
COPY package.json .
COPY package-lock.json .

# Install app dependencies.
RUN npm install

# Copy app files.
COPY . /app

EXPOSE 4200

# run app
CMD ["npm", "start"]
